variable "name" {
  description = "Database identifier"
  type        = string
}

variable "engine" {
  description = "Database engine"
  type        = string
  default     = "postgres"

  validation {
    condition     = contains(["postgres", "mysql"], var.engine)
    error_message = "engine must be postgres or mysql."
  }
}

variable "engine_version" {
  description = "Engine version"
  type        = string
  default     = "16.6"
}

variable "instance_class" {
  description = "Instance size"
  type        = string
  default     = "db.t4g.medium"
}

variable "allocated_storage" {
  description = "Initial storage in GiB"
  type        = number
  default     = 50
}

variable "max_allocated_storage" {
  description = "Upper bound for storage autoscaling"
  type        = number
  default     = 500
}

variable "database_name" {
  description = "Initial database created on the instance"
  type        = string
}

variable "master_username" {
  description = "Master username. The password is generated by AWS and stored in Secrets Manager — never set one here."
  type        = string
  default     = "dbadmin"
}

variable "vpc_id" {
  description = "VPC the database lives in"
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnets for the DB subnet group"
  type        = list(string)

  validation {
    condition     = length(var.private_subnet_ids) >= 2
    error_message = "RDS requires subnets in at least two availability zones."
  }
}

variable "allowed_security_group_ids" {
  description = "Security groups permitted to connect. Access is deny-all until something is listed here."
  type        = list(string)
  default     = []
}

variable "multi_az" {
  description = "Run a standby in a second availability zone"
  type        = bool
  default     = true
}

variable "backup_retention_period" {
  description = "Days of automated backups"
  type        = number
  default     = 30

  validation {
    condition     = var.backup_retention_period >= 7
    error_message = "Retain at least 7 days of backups."
  }
}

variable "deletion_protection" {
  description = "Block accidental deletion"
  type        = bool
  default     = true
}

variable "tags" {
  description = "Tags applied to every resource"
  type        = map(string)
  default     = {}
}
